plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/franvilchez/Kerma/pc-setup/web"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "https://raw.githubusercontent.com/Vilchaco/kerma-pc-setup/main/bootstrap.ps1"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "https://raw.githubusercontent.com/Vilchaco/kerma-pc-setup/main/bootstrap.ps1"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]